# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'scout-viewer-2015-iOS' do
    
    pod 'Firebase', '>= 2.5.0'
    pod 'JBChartView'
    pod 'Sync'
    pod 'HanekeSwift'
    pod 'Instabug'
    pod 'MWPhotoBrowser'
end


