# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'scout-viewer-2015-iOS' do

	pod 'CCDropboxRealmSync-iOS', :git => 'https://github.com/frc1678/CCDropboxRealmSync-iOS'
	pod 'realm-database-2015', :git => 'https://github.com/frc1678/realm-database-2015'
	pod 'MWPhotoBrowser', :git => 'https://github.com/mwaterfall/MWPhotoBrowser.git'
	pod 'JBChartView'
end


