//
//  CalculatedTeamData.swift
//  scout-viewer-2015-iOS
//
//  Created by Samuel Resendez on 1/23/16.
//  Copyright © 2016 Citrus Circuits. All rights reserved.
//

import UIKit

@objc class CalculatedTeamData: NSObject, Reflectable {
    
    var predictedSuccessfulCrossingsForDefenseTele = NSDictionary?()
    var avgLowShotsAttemptedTele = NSNumber?()
    var teleopShotAbility = NSNumber?()
    var actualSeed = NSNumber?()
    var avgBallControl = NSNumber?()
    var avgBallsKnockedOffMidlineAuto = NSNumber?()
    var avgDefense = NSNumber?()
    var avgEvasion = NSNumber?()
    var avgFailedTimesCrossedDefensesAuto = NSDictionary?()
    var avgFailedTimesCrossedDefensesTele = NSDictionary?()
    var avgTimeForDefenseCrossTele = NSDictionary?()
    var avgTimeForDefenseCrossAuto = NSDictionary?()
    var avgGroundIntakes = NSNumber?()
    var avgHighShotsAuto = NSNumber?()
    var avgHighShotsTele = NSNumber?()
    var avgHighShotsAttemptedTele = NSNumber?()
    var avgHighShotsAttemptedAuto = NSNumber?()
    var avgLowShotsAuto = NSNumber?()
    var avgLowShotsTele = NSNumber?()
    var avgShotsBlocked = NSNumber?()
    var autoAbility = NSNumber?()
    var avgMidlineBallsIntakedAuto = NSNumber?()
    var avgSpeed = NSNumber?()
    var avgSuccessfulTimesCrossedDefensesAuto = NSDictionary?()
    var avgSuccessfulTimesCrossedDefensesTele = NSDictionary?()
    var avgTorque = NSNumber?()
    var challengePercentage = NSNumber?()
    var disabledPercentage = NSNumber?()
    var disfunctionalPercentage = NSNumber?()
    var driverAbility = NSNumber?()
    var firstPickAbility = NSNumber?()
    var highShotAccuracyAuto = NSNumber?()
    var highShotAccuracyTele = NSNumber?()
    var incapacitatedPercentage = NSNumber?()
    var lowShotAccuracyAuto = NSNumber?()
    var lowShotAccuracyTele = NSNumber?()
    var numAutoPoints = NSNumber?()
    var actualNumRPs = NSNumber?()
    var predictedNumRPs = NSNumber?()
    var numScaleAndChallengePoints = NSNumber?()
    var predictedSeed = NSNumber?()
    var reachPercentage = NSNumber?()
    var scalePercentage = NSNumber?()
    var sdBallsKnockedOffMidlineAuto = NSNumber?()
    var sdFailedDefenseCrossesAuto = NSDictionary?()
    var sdFailedDefenseCrossesTele = NSDictionary?()
    var sdGroundIntakes = NSNumber?()
    var sdHighShotsAuto = NSNumber?()
    var sdHighShotsTele = NSNumber?()
    var sdLowShotsAuto = NSNumber?()
    var sdLowShotsTele = NSNumber?()
    var sdMidlineBallsIntakedAuto = NSNumber?()
    var sdShotsBlocked = NSNumber?()
    var sdSuccessfulDefenseCrossesAuto = NSDictionary?()
    var sdSuccessfulDefenseCrossesTele = NSDictionary?()
    var RScoreDrivingAbility = NSNumber?()
    var RScoreSpeed = NSNumber?()
    var RScoreTorque = NSNumber?()
    var RScoreAgility = NSNumber?()
    var RScoreDefense = NSNumber?()
    var RScoreBallControl = NSNumber?()
    var secondPickAbility = NSDictionary?()
    var siegeAbility = NSNumber?()
    var siegeConsistency = NSNumber?()
    var siegePower = NSNumber?()
    var overallSecondPickAbility = NSNumber?()
    var citrusDPR = NSNumber?()
    //var avgSuccessfulTimesCrossedDefenses = NSDictionary?()
    
    }
