//
//  CalculatedTeamData.swift
//  scout-viewer-2015-iOS
//
//  Created by Samuel Resendez on 1/23/16.
//  Copyright © 2016 Citrus Circuits. All rights reserved.
//

import UIKit

@objc class CalculatedTeamData: NSObject, Reflectable {
    
    var predictedSuccessfulCrossingsForDefenseTele = NSDictionary?.init(nilLiteral: ())
//    var avgLowShotsAttemptedTele = NSNumber?.init(nilLiteral: ())
    var avgLowShotsAttemptedTele: NSNumber? = nil

    var teleopShotAbility = NSNumber?.init(nilLiteral: ())
    var actualSeed = NSNumber?.init(nilLiteral: ())
    var avgBallControl = NSNumber?.init(nilLiteral: ())
    var avgBallsKnockedOffMidlineAuto = NSNumber?.init(nilLiteral: ())
    var avgDefense = NSNumber?.init(nilLiteral: ())
    var avgEvasion = NSNumber?.init(nilLiteral: ())
    var avgFailedTimesCrossedDefensesAuto = NSDictionary?.init(nilLiteral: ())
    var avgFailedTimesCrossedDefensesTele = NSDictionary?.init(nilLiteral: ())
    var avgTimeForDefenseCrossTele = NSDictionary?.init(nilLiteral: ())
    var avgTimeForDefenseCrossAuto = NSDictionary?.init(nilLiteral: ())
    var avgGroundIntakes = NSNumber?.init(nilLiteral: ())
    var avgHighShotsAuto = NSNumber?.init(nilLiteral: ())
    var avgHighShotsTele = NSNumber?.init(nilLiteral: ())
    var avgHighShotsAttemptedTele = NSNumber?.init(nilLiteral: ())
    var avgHighShotsAttemptedAuto = NSNumber?.init(nilLiteral: ())
    var avgLowShotsAuto = NSNumber?.init(nilLiteral: ())
    var avgLowShotsTele = NSNumber?.init(nilLiteral: ())
    var avgNumTimesCrossedDefensesAuto = NSNumber?.init(nilLiteral: ())
    var avgShotsBlocked = NSNumber?.init(nilLiteral: ())
    var autoAbility = NSNumber?.init(nilLiteral: ())
    var avgMidlineBallsIntakedAuto = NSNumber?.init(nilLiteral: ())
    var avgSpeed = NSNumber?.init(nilLiteral: ())
    var avgSuccessfulTimesCrossedDefensesAuto = NSDictionary?.init(nilLiteral: ())
    var avgSuccessfulTimesCrossedDefensesTele = NSDictionary?.init(nilLiteral: ())
    var avgTorque = NSNumber?.init(nilLiteral: ())
    var challengePercentage = NSNumber?.init(nilLiteral: ())
    var disabledPercentage = NSNumber?.init(nilLiteral: ())
    var disfunctionalPercentage = NSNumber?.init(nilLiteral: ())
    var driverAbility = NSNumber?.init(nilLiteral: ())
    var firstPickAbility = NSNumber?.init(nilLiteral: ())
    var highShotAccuracyAuto = NSNumber?.init(nilLiteral: ())
    var highShotAccuracyTele = NSNumber?.init(nilLiteral: ())
    var incapacitatedPercentage = NSNumber?.init(nilLiteral: ())
    var lowShotAccuracyAuto = NSNumber?.init(nilLiteral: ())
    var lowShotAccuracyTele = NSNumber?.init(nilLiteral: ())
    var numAutoPoints = NSNumber?.init(nilLiteral: ())
    var actualNumRPs = NSNumber?.init(nilLiteral: ())
    var predictedNumRPs = NSNumber?.init(nilLiteral: ())
    var numScaleAndChallengePoints = NSNumber?.init(nilLiteral: ())
    var predictedSeed = NSNumber?.init(nilLiteral: ())
    var reachPercentage = NSNumber?.init(nilLiteral: ())
    var scalePercentage = NSNumber?.init(nilLiteral: ())
    var sdBallsKnockedOffMidlineAuto = NSNumber?.init(nilLiteral: ())
    var sdFailedDefenseCrossesAuto = NSDictionary?.init(nilLiteral: ())
    var sdFailedDefenseCrossesTele = NSDictionary?.init(nilLiteral: ())
    var sdGroundIntakes = NSNumber?.init(nilLiteral: ())
    var sdHighShotsAuto = NSNumber?.init(nilLiteral: ())
    var sdHighShotsTele = NSNumber?.init(nilLiteral: ())
    var sdLowShotsAuto = NSNumber?.init(nilLiteral: ())
    var sdLowShotsTele = NSNumber?.init(nilLiteral: ())
    var sdMidlineBallsIntakedAuto = NSNumber?.init(nilLiteral: ())
    var sdShotsBlocked = NSNumber?.init(nilLiteral: ())
    var sdSuccessfulDefenseCrossesAuto = NSDictionary?.init(nilLiteral: ())
    var sdSuccessfulDefenseCrossesTele = NSDictionary?.init(nilLiteral: ())
    var RScoreDrivingAbility = NSNumber?.init(nilLiteral: ())
    var RScoreSpeed = NSNumber?.init(nilLiteral: ())
    var RScoreTorque = NSNumber?.init(nilLiteral: ())
    var RScoreAgility = NSNumber?.init(nilLiteral: ())
    var RScoreDefense = NSNumber?.init(nilLiteral: ())
    var RScoreBallControl = NSNumber?.init(nilLiteral: ())
    var secondPickAbility = NSDictionary?.init(nilLiteral: ())
    var siegeAbility = NSNumber?.init(nilLiteral: ())
    var siegeConsistency = NSNumber?.init(nilLiteral: ())
    var siegePower = NSNumber?.init(nilLiteral: ())
    var overallSecondPickAbility = NSNumber?.init(nilLiteral: ())
    var citrusDPR = NSNumber?.init(nilLiteral: ())
    var beachedPercentage = NSDictionary?.init(nilLiteral: ())
    var slowedPercentage = NSDictionary?.init(nilLiteral: ())
    var defensesCrossableAuto = NSString?.init(nilLiteral: ())
    var twoBallAutoTriedPercentage = NSNumber?.init(nilLiteral: ())
    var twoBallAutoAccuracy = NSNumber?.init(nilLiteral: ())
    }
